function InsertUtilityDiv() { return ''; }
function BESFixletID() { return ''; }
function BESFixletIDToString() { return ''; }
function MakeIDListFromArray() { return ''; }
function ActivateAnalysis() { return ''; }
function ActivateAnalyses() { return ''; }
function ReactivateAnalysis() { return ''; }
function ReactivateAnalyses() { return ''; }
function DeactivateAnalysis() { return ''; }
function DeactivateAnalyses() { return ''; }
function StopAction() { return ''; }
function StopActions() { return ''; }
function ImportXML() { return ''; }
function ImportXMLToSite() { return ''; }
function EvaluateRelevance() { return ''; }
function Relevance() { return ''; }
function RegisterRelevance() { return ''; }
function BooleanToText() { return ''; }
function DoBrowseDialogWithFlags() { return ''; }
function BrowseForFile() { return ''; }
function BrowseForFolder() { return ''; }
function RegisterRefreshHandler() { return ''; }
function LoadPresentation() { return ''; }
function GetScratchRootPath() { return ''; }
function MakeArchive() { return ''; }
function CopyFile() { return ''; }
function MoveFile() { return ''; }
function DeleteFile() { return ''; }
function DeleteAllFiles() { return ''; }
function DeleteFolder() { return ''; }
function DeleteTree() { return ''; }
function MakeFolder() { return ''; }
function CopyFolder() { return ''; }
function WriteFile() { return ''; }
function UploadFile() { return ''; }
function UploadFileWithName() { return ''; }
function ArchiveAndUploadFile() { return ''; }
function ArchiveAndUploadFile2() { return ''; }
function DownloadFile() { return ''; }
function DownloadFileWithSHA1() { return ''; }
function GetFileSHA1() { return ''; }
function GetFileSize() { return ''; }
function GetCurrentDSN() { return ''; }
function GetCurrentUser() { return ''; }
function ManualRefresh() { return ''; }
function ManualRefreshAll() { return ''; }
function OpenComputerGroup() { return ''; }
function SendWakeOnLANRequest() { return ''; }
function ColorizeRelevance() { return ''; }
function StoreVariable() { return ''; }
function StorePrivateVariable() { return ''; }
function StoreSharedVariable() { return ''; }
function DeleteVariable() { return ''; }
function DeletePrivateVariable() { return ''; }
function DeleteSharedVariable() { return ''; }
function EditFixlet() { return ''; }
function DeleteFixlet() { return ''; }
function DeleteFixlets() { return ''; }
function DeleteProperty() { return ''; }
function DeleteProperties() { return ''; }
function TakeFixletAction() { return ''; }
function TakeSecureFixletAction() { return ''; }
function TakeFixletActionOnComputers() { return ''; }
function TakeSecureFixletActionOnComputers() { return ''; }
function OpenVisualization() { return ''; }
function AddGlobalFilter() { return ''; }
function ClearAllGlobalFilters() { return ''; }
function ClearGlobalFilterOfType() { return ''; }
function EnableWakeOnLAN() { return ''; }
function CreateCustomSite() { return ''; }
function EnableExternalSite() { return ''; }
function AddFileToMailbox() { return ''; }
function AddFileToSite() { return ''; }
function DownloadFileEx() { return ''; }
function UploadFileEx() { return ''; }
function ArchiveAndUploadFileEx() { return ''; }
function CompleteHashSet() { return ''; }
function CalculateFileInfo() { return ''; }
function SiteCertificateUpdateNeeded() { return ''; }
function CreateFastQuestion() { return ''; }
function GetFastQuestionResults() { return ''; }
