---
name: test_repo_dispatch
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch

# trigger this with:
# { "event_type": "test_repo_dispatch", "client_payload": { "message": "Put Status Message Here!" } }
# curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <YOUR-TOKEN>" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/jgstew/tools/dispatches -d '{ "event_type": "test_repo_dispatch", "client_payload": { "message": "Put Status Message Here!" } }'
# OR:
# gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/jgstew/tools/dispatches -f "event_type=test_repo_dispatch" -F "client_payload[message]=test message"

on:
  repository_dispatch:
    types: [test_repo_dispatch]

jobs:
  test_repo_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input to Summary
        run: |
          echo "## Message:" >> $GITHUB_STEP_SUMMARY
          echo ${{ github.event.client_payload.message }} >> $GITHUB_STEP_SUMMARY
          echo "## Event Type:" >> $GITHUB_STEP_SUMMARY
          echo ${{ github.event.action }} >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
